# 测试用例文件
file: test_fish_pay.py
# 测试用例类（用例类参数和用例函数参数都为空时，则运行整个用例文件）
class: TestFishPay
# 测试用例函数（仅用例函数参数为空时，则运行整个用例类）
case: test_fish_pay_success
# 描述
desc: 【壁纸】鱼干支付-预期成功
params:
  # 接口地址
  server_origin: http://test-pcwallpaper.zhhainiao.com
  # 管理后台接口地址
  cms_origin: http://wprmmgr.aix-test-k8s.iweikan.cn
  # 创建会员账号类型
  user_identity:
    - NON_VIP
