# 测试用例文件
file: test_popularity_author_follow.py
# 测试用例类（用例类参数和用例函数参数都为空时，则运行整个用例文件）
class: TestPopularityAuthorFollow
# 测试用例函数（仅用例函数参数为空时，则运行整个用例类）
case: test_popularity_author_follow_success
# 描述
desc: 【壁纸】人气作者专区关注-预期成功
params:
  # 接口地址
  server_origin: http://test-pcwallpaper.zhhainiao.com
  # 创建会员账号类型
  user_identity:
    - NON_VIP
