# 测试用例文件
file: test_member_benefits.py
# 测试用例类（用例类参数和用例函数参数都为空时，则运行整个用例文件）
class: TestPermission
# 测试用例函数（仅用例函数参数为空时，则运行整个用例类）
case: test_user_permission
# 描述
desc: 权益会员权限查询-预期成功
params:
  # 接口版本
  product_type: []
  # 创建帐号接口地址
  account_origin: http://62.234.196.151
  # 用户接口地址
  user_origin: http://62.234.196.151
  # 网关接口地址
  gateway_origin: http://newvip-dev-gw.duba.net
  # 创建会员账号类型
  user_identity:
    - NON_VIP
    - NORMAL_VIP
