# 测试用例文件
file: test_member_benefits.py
# 测试用例类（用例类参数和用例函数参数都为空时，则运行整个用例文件）
class: TestPermission
# 测试用例函数
case: test_change_user_permission
# 描述
desc: 检验用户权益下单-预期成功
params:
  # 接口版本
  product_type: []
  # 创建帐号接口地址
  account_origin: http://newvip-dev2.duba.net
  # 用户接口地址
  user_origin: http://newvip-dev2.duba.net
  # 网关接口地址
  gateway_origin: http://newvip-dev-gw.duba.net
  # 支付接口地址
  pay_origin: http://newvip-dev2.duba.net
  # 第三方支付Mock接口地址
  fake_pay_origin: http://fakepayserver.aix-test-k8s.iweikan.cn
  # 创建会员账号类型
  user_identity:
    - NON_VIP
  # 支付类型（目前服务端仅Mock了微信扫码支付的类型）
  pay_type:
    - WECHAT_QRCODE
  # 修改与查询间隔时间（秒）
  query_sleep_seconds: 3
  # 权益会员套餐
  permission_pay_setting: PDF_CONVERT_WEB
