# 测试用例文件
file: test_modify_user_info.py
# 测试用例类（用例类参数和用例函数参数都为空时，则运行整个用例文件）
class: TestModifyUserInfo
# 测试用例函数（仅用例函数参数为空时，则运行整个用例类）
case: test_modify_forbid_failure
# 描述
desc: 修改用户信息-预期失败
params:
  # 接口版本
  product_type: []
  # 创建帐号接口地址
  account_origin: http://newvip-dev2.duba.net
  # 用户接口地址
  user_origin: http://newvip-dev2.duba.net
  # 网关接口地址
  gateway_origin: http://newvip-dev-gw.duba.net
  # 创建会员账号类型
  user_identity:
    - NON_VIP
  # 修改与查询间隔时间（秒）
  query_sleep_seconds: 5
